version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app:cached
      - ./data/database.db:/app/database.db
    ports:
      - "8000:8000"
    environment:
      # Force sqlite path (4 slashes = absolute path)
      - DATABASE_URL=sqlite:////app/database.db
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3